### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by r-pascua** [UPennEoR/RIMEz#12]
Some of the code is formatted in a way that works in Py2 but breaks in Py3. This should be fixed.

**Comment by r-pascua** [comment]
Notes for making Py3 compatible:
- There are a few `print` statements floating around in the codebase that are currently not Py3 compatible. Some modules I've found them in:
  - `management`
  - `beam_models`
  - `spin1_beam_model.jones_matrix_field`
  - `numba_ssht.test_numba_wrappers`
- Imports need to be updated (e.g. `import management` -> `from . import management`)
- `spin1_beam_model` requires some special handling (either adding its location to the python path or moving it and importing it in the `RIMEz` constructor)
- `sky_models` uses `itertools.izip`, which doesn't exist in Py3 (the functionality now exists in the builtin `zip`). In my local branch I did the following change (kind of ugly, but it works):
```
import sys
if sys.version_info.major < 3:
    from itertools import izip
else:
    izip = zip
```

**Comment by plaplant** [comment]
My vote is to break python2 compatibility and just make everything python3. It makes us future-proof, and then we don't have to worry about juggling things with `six` come 2020.

**Comment by steven-murray** [comment]
Does the current version now work for py3? We should get CI setup ASAP to check these things (even with the most basic testing).

**Comment by Jackmastr** [comment]
Was this ever resolved?

**Comment by steven-murray** [comment]
It looks like the travis runs are passing for 3.6 and 3.7 (and no tests being run for 2.x), so yes, I'd say it was resolved :-)
