### ISSUE TITLE
setup.py requirements

### ISSUE THREAD

**Issue by steven-murray** [UPennEoR/RIMEz#2]
The setup.py should have all the requirements to be able to install `RIMEz` without the user doing anything on top of `pip install RIMEz`. Requirements that are only available on Github can still be specified in the setup.py

**Comment by r-pascua** [comment]
I'm currently working on getting `RIMEz` running on my local machine. I figure it'll be helpful to list all of the dependency issues I run into, so here's a list of stuff beyond what is already listed, to be updated as I finish the setup:
- `h5py`
- `gitpython`
- ...
