### ISSUE TITLE
numba: deprecated module cffi_support has been removed

### ISSUE THREAD

**Issue by lbfinkbeiner** [UPennEoR/RIMEz#26]
Low priority issue, since it is easily user-fixable by manually installing numba=0.48. I believe, at least, that the setup script should explicitly require numba <= 0.48.

If it is important, going forward, to stay in pace with numba releases, all references to cffi_support must be updated (cffi_support is no longer a member of numba). Otherwise, this code will not run with modern versions of numba (latest stable on conda is 0.50.1).

**Comment by steven-murray** [comment]
@lbfinkbeiner thanks for pointing this out! 

Can you make a PR updating to the latest version of numba, and we'll see if tests run?

@zacharymartinot any point supporting pre-0.48 versions of numba?

**Comment by lbfinkbeiner** [comment]
First of all, I apologize. I did not pay enough attention to the stack trace, and the true source of the problem was ssht_numba, a separate UPennEoR repository.

Second, I tried to test my fix (a PR has been issued to ssht_numba) by re-running my application (which interfaces directly with RIMEz). I received the error that "dfitpack_wrappers.so" was not found in in the "dfitpack_wrappers" directory. **However**, I did not get this issue when I uninstalled RIMEz (using the developer instructions) and reinstalled for general use.

Now, I do not have any experience developing RIMEz directly, and it somewhat strikes me that that error that I encountered is not relevant to this numba issue. Consequently, I think that you can close this issue once you read this.

**Comment by steven-murray** [comment]
Ah, OK thanks!
